---
- name: Prepare
  hosts: all
  become_user: root
  tasks:
    - name: Display Ansible version
      debug:
        msg: "Ansible version is  {{ ansible_version.full }}"

    - name: Install required dependencies
      package:
        name: sudo